# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cucumber_spinner}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Tobias Kraze}]
  s.date = %q{2012-07-05}
  s.description = %q{Formatter for cucumber like the RSpecSpinner for RSpec. Shows a progress bar on the command line, prints failing scenarios immediately and can automatically show a browser dump of the error page.}
  s.email = %q{tobias.kraze@makandra.de}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "cucumber_spinner.gemspec",
    "lib/cucumber_spinner.rb",
    "lib/cucumber_spinner/curious_progress_bar_formatter.rb",
    "lib/cucumber_spinner/formatted_io.rb",
    "lib/cucumber_spinner/progress_bar_formatter.rb",
    "lib/cucumber_spinner/time_judge.rb"
  ]
  s.homepage = %q{http://github.com/makandra/cucumber_spinner}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Progress bar formatter for cucumber, shows failing scenarios immediately.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rtui>, [">= 0.2.2"])
    else
      s.add_dependency(%q<rtui>, [">= 0.2.2"])
    end
  else
    s.add_dependency(%q<rtui>, [">= 0.2.2"])
  end
end

